services:
  app:
    build: .
    container_name: express_app
    env_file: .env
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - minio
      - redis
      - traefik
    restart: unless-stopped
    volumes:
      - temp_zips:/app/temp_zips
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cloudisy_net

  upload_worker:
    build: .
    container_name: upload_w
    env_file: .env
    command: ["node", "dist/src/queue/workers/upload.worker.js"]
    depends_on:
      - redis
      - db
    restart: unless-stopped
    volumes:
      - temp_zips:/app/temp_zips
    networks:
      - cloudisy_net

  log_worker:
    build: .
    container_name: log_w
    env_file: .env
    command: ["node", "dist/src/queue/workers/log.worker.js"]
    depends_on:
      - redis
      - db
    restart: unless-stopped
    networks:
      - cloudisy_net

  sync_worker:
    build: .
    container_name: sync_w
    env_file: .env
    command: ["node", "dist/src/queue/workers/sync.worker.js"]
    depends_on:
      - redis
      - db
    restart: unless-stopped
    networks:
      - cloudisy_net


  database_worker:
    build: .
    container_name: database_w
    env_file: .env
    command: ["node", "dist/src/queue/workers/database.worker.js"]
    depends_on:
      - redis
      - db
      - traefik
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cloudisy_net

  caddy:
    image: caddy:2-alpine
    container_name: caddy_server
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - cloudisy_net

  traefik:
    image: traefik:v3.1
    container_name: traefik_server
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "8080:8080"
      - "15432-15462:15432-15462"
    volumes:
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - cloudisy_net

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - cloudisy_net

  minio:
    image: minio/minio
    container_name: minio_server
    env_file: .env
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - miniodata:/data
    restart: always
    networks:
      - cloudisy_net

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server
    expose:
      - "6379"
    restart: unless-stopped
    networks:
      - cloudisy_net

  vector:
    image: timberio/vector:0.38.0-alpine
    container_name: vector
    env_file: .env
    command: ["--config", "/etc/vector/vector.toml"]
    volumes:
      - caddy_logs:/var/log/caddy:ro
      - ./config/vector.toml:/etc/vector/vector.toml:ro
      - vector_data:/var/lib/vector
    depends_on:
      - caddy
      - app
    restart: unless-stopped
    networks:
      - cloudisy_net

volumes:
  pgdata:
  miniodata:
  caddy_data:
  caddy_config:
  vector_data:
  temp_zips:
  caddy_logs:

networks:
  cloudisy_net:
    name: cloudisy_net
